import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let d=new Uint8ClampedArray(64*64*4),u=[],r=[],tool='brush',brush=1,opacity=1,fg='#4aa3ff',grid=true,db;
const c=$('#skinCanvas'),x=c.getContext('2d'),w=document.createElement('canvas');w.width=w.height=64;const wx=w.getContext('2d'),tex=new THREE.CanvasTexture(w);tex.magFilter=THREE.NearestFilter;tex.minFilter=THREE.NearestFilter;
const px=(a,b,v)=>a>=0&&b>=0&&a<64&&b<64&&d.set(v,(b*64+a)*4),get=(a,b)=>d.slice((b*64+a)*4,(b*64+a+1)*4),col=h=>{h=h.slice(1);return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16),255]};
function sync(){let i=x.createImageData(64,64);i.data.set(d);x.putImageData(i,0,0);wx.putImageData(i,0,0);tex.needsUpdate=true;if(grid){x.strokeStyle='#ffffff22';x.lineWidth=.05;for(let i=0;i<65;i++){x.beginPath();x.moveTo(i,0);x.lineTo(i,64);x.stroke();x.beginPath();x.moveTo(0,i);x.lineTo(64,i);x.stroke()}}}
function blank(){d.fill(0);for(let y=0;y<8;y++)for(let z=0;z<8;z++)px(8+z,8+y,[210,165,125,255]);for(let y=0;y<12;y++)for(let z=0;z<8;z++)px(16+z,16+y,[55,90,145,255]);for(let y=0;y<12;y++)for(let z=0;z<4;z++){px(40+z,16+y,[45,70,110,255]);px(32+z,48+y,[45,70,110,255]);px(z,16+y,[40,48,58,255]);px(16+z,48+y,[40,48,58,255])}sync();save()}
function saveState(){u.push(new Uint8ClampedArray(d));if(u.length>100)u.shift();r=[];save()}function undo(){if(u.length){r.push(new Uint8ClampedArray(d));d=u.pop();sync();save()}}function redo(){if(r.length){u.push(new Uint8ClampedArray(d));d=r.pop();sync();save()}}
function point(e){let q=c.getBoundingClientRect();return[Math.floor((e.clientX-q.left)/q.width*64),Math.floor((e.clientY-q.top)/q.height*64)]}function paint(a,b){let cc=tool==='eraser'?[0,0,0,0]:col(fg),n=Math.max(1,brush);for(let yy=b-n+1;yy<b+n;yy++)for(let xx=a-n+1;xx<a+n;xx++){let old=get(xx,yy),k=opacity;px(xx,yy,cc[3]===0?cc:[old[0]*(1-k)+cc[0]*k,old[1]*(1-k)+cc[1]*k,old[2]*(1-k)+cc[2]*k,255]);if($('#mirrorX').classList.contains('active'))px(63-xx,yy,get(xx,yy));if($('#mirrorY').classList.contains('active'))px(xx,63-yy,get(xx,yy))}}
let down=false;c.onpointerdown=e=>{down=true;saveState();paint(...point(e));sync()};c.onpointermove=e=>{let p=point(e);$('#cursorPos').textContent=`x: ${p[0]} y: ${p[1]}`;if(down){paint(...p);sync()}};onpointerup=()=>{down=false;save()};
const renderer=new THREE.WebGLRenderer({canvas:$('#threeCanvas'),alpha:true,antialias:true,preserveDrawingBuffer:true});const scene=new THREE.Scene(),cam=new THREE.PerspectiveCamera(35,1,.1,100),g=new THREE.Group();scene.add(g,new THREE.HemisphereLight(0xffffff,0x333333,2));let light=new THREE.DirectionalLight(0xffffff,2);light.position.set(4,8,6);scene.add(light);let meshes={};
function build(){g.clear();meshes={};[['head',[0,4.8,0],[2,2,2]],['body',[0,2.4,0],[2,2.6,1]],['rightArm',[-1.5,2.4,0],[.8,2.6,1]],['leftArm',[1.5,2.4,0],[.8,2.6,1]],['rightLeg',[-.5,0,0],[.95,2.6,1]],['leftLeg',[.5,0,0],[.95,2.6,1]]].forEach(([n,p,s])=>{let m=new THREE.Mesh(new THREE.BoxGeometry(...s),new THREE.MeshStandardMaterial({map:tex,transparent:true,alphaTest:.02}));m.name=n;m.position.set(...p);g.add(m);meshes[n]=m});fit()}
let yaw=.3,dist=9;function fit(){cam.position.set(Math.sin(yaw)*dist,4.1,Math.cos(yaw)*dist);cam.lookAt(0,2.5,0);resize()}function resize(){let q=$('#viewport3d').getBoundingClientRect();renderer.setSize(q.width,q.height,false);cam.aspect=q.width/q.height;cam.updateProjectionMatrix();renderer.render(scene,cam)}$('#threeCanvas').onpointerdown=()=>down=true;$('#threeCanvas').onpointermove=e=>{if(down){yaw+=(e.movementX||0)*.01;fit()}};$('#threeCanvas').onpointerup=()=>down=false;$('#threeCanvas').onwheel=e=>{dist=Math.max(4,Math.min(18,dist+e.deltaY*.01));fit()};
function importPNG(f){let im=new Image;im.onload=()=>{if(im.width!==64||im.height!==64)return toast('Minecraft skin PNGs must be 64×64');let z=document.createElement('canvas');z.width=z.height=64;let q=z.getContext('2d');q.drawImage(im,0,0);d=new Uint8ClampedArray(q.getImageData(0,0,64,64).data);u=[];r=[];sync();save();toast('Imported')};im.src=URL.createObjectURL(f)}function download(){let a=document.createElement('a');a.href=c.toDataURL();a.download='skinforge-skin.png';a.click()}
function toast(s){let q=$('#toast');q.textContent=s;q.classList.add('show');setTimeout(()=>q.classList.remove('show'),1500)}
async function openDB(){return new Promise((ok,no)=>{let q=indexedDB.open('skinforge',1);q.onupgradeneeded=()=>q.result.createObjectStore('skins',{keyPath:'id'});q.onsuccess=()=>{db=q.result;ok()};q.onerror=no})}function save(){if(db)db.transaction('skins','readwrite').objectStore('skins').put({id:'current',texture:Array.from(d),updated:Date.now()})}async function load(){let q=await new Promise((ok,no)=>{let z=db.transaction('skins').objectStore('skins').get('current');z.onsuccess=()=>ok(z.result);z.onerror=no});if(q){d=new Uint8ClampedArray(q.texture);sync()}}
$$('.tool').forEach(b=>b.onclick=()=>{$$('.tool').forEach(z=>z.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool});$('#brushSize').oninput=e=>brush=+e.target.value;$('#opacity').oninput=e=>opacity=+e.target.value/100;$('#fgColor').oninput=e=>fg=e.target.value;['mirrorX','mirrorY','mirrorLimb'].forEach(z=>$('#'+z).onclick=()=>$('#'+z).classList.toggle('active'));$('#gridBtn').onclick=()=>{grid=!grid;sync()};$('#fitBtn').onclick=fit;$('#newBtn').onclick=blank;$('#openBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>e.target.files[0]&&importPNG(e.target.files[0]);$('#downloadBtn').onclick=download;$('#saveBtn').onclick=save;$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#fullscreenBtn').onclick=()=>document.documentElement.requestFullscreen?.();$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(z=>z.classList.remove('active'));b.classList.add('active');$('#viewport3d').classList.toggle('hidden',b.dataset.mode!=='3d');$('#viewport2d').classList.toggle('hidden',b.dataset.mode!=='2d');if(b.dataset.mode==='3d')resize()});
$$('[data-menu]').forEach(b=>b.onclick=()=>{let m={file:[['New',blank],['Open',()=>$('#fileInput').click()],['Save',save],['Export PNG',download]],edit:[['Undo',undo],['Redo',redo]],view:[['Fullscreen',()=>document.documentElement.requestFullscreen?.()],['Grid',()=>$('#gridBtn').click()],['Fit',fit]],settings:[['Preferences',()=>alert('Local settings and cloud configuration are documented in README.md')]],help:[['About',()=>alert('SkinForge — independent browser-based Minecraft skin editor.')]]}[b.dataset.menu],p=$('#menuPanel');p.innerHTML=m.map((z,i)=>`<button>${z[0]}</button>`).join('');p.classList.remove('hidden');p.querySelectorAll('button').forEach((z,i)=>z.onclick=()=>{p.classList.add('hidden');m[i][1]()})});
window.onresize=resize;window.onoffline=()=>$('#syncState').textContent='Offline';window.ononline=()=>$('#syncState').textContent='Online';async function init(){await openDB();await load();if(!d.some(Boolean))blank();build();sync();resize()}init();