import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],SIZE=64,PIXELS=16384;
let d=new Uint8ClampedArray(PIXELS),undoStack=[],redoStack=[],tool='brush',brushSize=1,opacity=1,intensity=1,fg='#4aa3ff',grid=true,uvOverlay=false,modelType=localStorage.getItem('skinforge:model')||'classic',outerVisible=true,bodyVisible=true,down=false,strokeStart=null,strokeBase=null,cloneSource=null,selection=null,db=null,pose={head:[0,0,0],leftArm:0,rightArm:0},referenceImage=null;
const skinCanvas=$('#skinCanvas'),ctx=skinCanvas.getContext('2d',{willReadFrequently:true}),textureCanvas=document.createElement('canvas');textureCanvas.width=textureCanvas.height=64;const textureCtx=textureCanvas.getContext('2d',{willReadFrequently:true}),texture=new THREE.CanvasTexture(textureCanvas);texture.magFilter=THREE.NearestFilter;texture.minFilter=THREE.NearestFilter;texture.generateMipmaps=false;texture.colorSpace=THREE.SRGBColorSpace;
const renderer=new THREE.WebGLRenderer({canvas:$('#threeCanvas'),alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.05,100),character=new THREE.Group();scene.add(character);scene.add(new THREE.HemisphereLight(0xffffff,0x30343b,2));const keyLight=new THREE.DirectionalLight(0xffffff,2.2);keyLight.position.set(5,9,7);scene.add(keyLight);
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),meshes={},partGroups={};let cameraYaw=.35,cameraPitch=.04,cameraDistance=9,cameraTarget=new THREE.Vector3(0,3.4,0),cameraDrag=null;
function px(x,y,v){if(x>=0&&y>=0&&x<64&&y<64)d.set(v,(y*64+x)*4)}function get(x,y){if(x<0||y<0||x>=64||y>=64)return[0,0,0,0];const i=(y*64+x)*4;return[d[i],d[i+1],d[i+2],d[i+3]]}function hex(h){h=h.replace('#','');if(h.length===3)h=h.split('').map(c=>c+c).join('');return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16),255]}function same(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]}function cloneData(){return new Uint8ClampedArray(d)}
function cleanPNGCanvas(){const o=document.createElement('canvas');o.width=o.height=64;o.getContext('2d').putImageData(textureCtx.getImageData(0,0,64,64),0,0);return o}window.SkinForge={getTextureData:cloneData,setTextureData:v=>{d=new Uint8ClampedArray(v);renderTexture()},getTextureDataUrl:()=>cleanPNGCanvas().toDataURL('image/png'),getModelType:()=>modelType,setModelType:v=>{if(v==='classic'||v==='slim'){modelType=v;localStorage.setItem('skinforge:model',v);buildCharacter()}}};
function drawGrid(){if(!grid)return;ctx.save();ctx.strokeStyle='rgba(255,255,255,.2)';ctx.lineWidth=.04;for(let i=0;i<=64;i++){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,64);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(64,i);ctx.stroke()}ctx.restore()}
function uvBoxes(){return[[8,0,24,16],[16,16,40,32],[0,16,16,32],[32,48,48,64],[16,48,32,64],[32,16,56,32],[16,32,40,48],[0,32,16,48]]}
function drawUV(){if(!uvOverlay)return;ctx.save();ctx.strokeStyle='rgba(74,163,255,.9)';ctx.lineWidth=.08;for(const b of uvBoxes()){ctx.strokeRect(b[0],b[1],b[2]-b[0],b[3]-b[1])}ctx.restore()}
function drawSelection(){if(!selection)return;ctx.save();ctx.fillStyle='rgba(80,160,255,.18)';for(const key of selection){const[a,b]=key.split(',').map(Number);ctx.fillRect(a,b,1,1)}ctx.restore()}
function renderTexture(){const im=textureCtx.createImageData(64,64);im.data.set(d);textureCtx.putImageData(im,0,0);texture.needsUpdate=true;ctx.clearRect(0,0,64,64);ctx.imageSmoothingEnabled=false;ctx.drawImage(textureCanvas,0,0);drawGrid();drawUV();drawSelection();$('#modelStatus').textContent=`${modelType==='slim'?'Alex':'Steve'} · 64×64`;if($('#modelType'))$('#modelType').value=modelType}
function saveState(){undoStack.push(cloneData());if(undoStack.length>100)undoStack.shift();redoStack=[];saveLocal()}function undo(){if(!undoStack.length)return;redoStack.push(cloneData());d=undoStack.pop();renderTexture();saveLocal()}function redo(){if(!redoStack.length)return;undoStack.push(cloneData());d=redoStack.pop();renderTexture();saveLocal()}
function point2D(e){const q=skinCanvas.getBoundingClientRect();return[Math.max(0,Math.min(63,Math.floor((e.clientX-q.left)/q.width*64))),Math.max(0,Math.min(63,Math.floor((e.clientY-q.top)/q.height*64)))]}
function brushPixels(cx,cy,fn){const n=Math.max(1,Math.round(brushSize)),r=(n-1)/2,shape=$('#brushShape')?.value||'Pixel';for(let y=Math.floor(cy-r);y<=Math.ceil(cy+r);y++)for(let x=Math.floor(cx-r);x<=Math.ceil(cx+r);x++){const dx=x-cx,dy=y-cy;let ok=shape==='Pixel'?(x===cx&&y===cy):shape==='Circle'?(dx*dx+dy*dy<=Math.max(1,r*r+r)):shape==='Triangle'?(Math.abs(dx)<=r&&dy>=-r&&dy<=r&&Math.abs(dx)<=r-(dy+r)/2+.5):true;if(ok)fn(x,y)}}
function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),l=(mx+mn)/2;let h=0,s=0;if(mx!==mn){const dd=mx-mn;s=l>.5?dd/(2-mx-mn):dd/(mx+mn);switch(mx){case r:h=(g-b)/dd+(g<b?6:0);break;case g:h=(b-r)/dd+2;break;default:h=(r-g)/dd+4}h/=6}return[h,s,l]}
function hue2rgb(p,q,t){if(t<0)t++;if(t>1)t--;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p}
function hslShift(c){let[h,s,l]=rgbToHsl(c[0],c[1],c[2]);h=(h+.08*intensity)%1;s=Math.max(0,Math.min(1,s+.15*intensity));const q=l<.5?l*(1+s):l+s-l*s,p=2*l-q;return[Math.round(255*hue2rgb(p,q,h+1/3)),Math.round(255*hue2rgb(p,q,h)),Math.round(255*hue2rgb(p,q,h-1/3)),255]}
function paintPixel(x,y,color){if(x<0||y<0||x>=64||y>=64)return;const old=get(x,y);if(color[3]===0){px(x,y,[0,0,0,0]);return}const a=opacity;px(x,y,[Math.round(old[0]*(1-a)+color[0]*a),Math.round(old[1]*(1-a)+color[1]*a),Math.round(old[2]*(1-a)+color[2]*a),255])}
function mirrorLimbPoint(x,y){const maps=[[40,56,16,32,32,48,48,64],[32,48,48,64,40,56,16,32],[0,16,16,32,16,32,48,64],[16,32,48,64,0,16,16,32]];for(const[a,b,c,e,f,g,h,i]of maps)if(x>=a&&x<b&&y>=c&&y<e)return[f+(x-a),g+(y-c)];return null}
function applyBrush(x,y){let color=tool==='eraser'?[0,0,0,0]:hex(fg);const mode=$('#brushMode')?.value||'smooth';brushPixels(x,y,(xx,yy)=>{let c=color;if(mode==='noise'&&c[3]){const n=(Math.random()-.5)*80*intensity;c=[Math.max(0,Math.min(255,c[0]+n)),Math.max(0,Math.min(255,c[1]+n)),Math.max(0,Math.min(255,c[2]+n)),255]}if(mode==='hsl'&&c[3])c=hslShift(c);if(tool==='clone'&&cloneSource)c=get(cloneSource[0]+xx-x,cloneSource[1]+yy-y);paintPixel(xx,yy,c);if($('#mirrorX')?.classList.contains('active'))paintPixel(63-xx,yy,get(xx,yy));if($('#mirrorY')?.classList.contains('active'))paintPixel(xx,63-yy,get(xx,yy));if($('#mirrorLimb')?.classList.contains('active')){const m=mirrorLimbPoint(xx,yy);if(m)paintPixel(m[0],m[1],get(xx,yy))}})}
function linePoints(x0,y0,x1,y1,fn){let dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,err=dx+dy;for(;;){fn(x0,y0);if(x0===x1&&y0===y1)break;const e=2*err;if(e>=dy){err+=dy;x0+=sx}if(e<=dx){err+=dx;y0+=sy}}}
function floodFill(x,y,color){const target=get(x,y);if(same(target,color))return;const q=[[x,y]],seen=new Set;while(q.length){const[a,b]=q.pop(),k=a+','+b;if(seen.has(k))continue;seen.add(k);if(!same(get(a,b),target))continue;px(a,b,color);if(a>0)q.push([a-1,b]);if(a<63)q.push([a+1,b]);if(b>0)q.push([a,b-1]);if(b<63)q.push([a,b+1])}}
function wandSelect(x,y){const target=get(x,y),q=[[x,y]],seen=new Set,out=new Set;while(q.length){const[a,b]=q.pop(),k=a+','+b;if(seen.has(k))continue;seen.add(k);if(!same(get(a,b),target))continue;out.add(k);if(a>0)q.push([a-1,b]);if(a<63)q.push([a+1,b]);if(b>0)q.push([a,b-1]);if(b<63)q.push([a,b+1])}selection=out;renderTexture()}
function applyAt(x,y){if(tool==='eyedropper'){const c=get(x,y);fg='#'+c.slice(0,3).map(v=>v.toString(16).padStart(2,'0')).join('');$('#fgColor').value=fg;return}if(tool==='fill'){floodFill(x,y,hex(fg));renderTexture();return}if(tool==='wand'){wandSelect(x,y);return}if(tool==='clone'&&!cloneSource){cloneSource=[x,y];toast('Clone source selected');return}if(tool==='line'&&strokeStart){linePoints(strokeStart[0],strokeStart[1],x,y,applyBrush);return}if(tool==='move'&&strokeStart){const dx=x-strokeStart[0],dy=y-strokeStart[1],old=strokeBase;d=new Uint8ClampedArray(PIXELS);for(let yy=0;yy<64;yy++)for(let xx=0;xx<64;xx++){const sx=xx-dx,sy=yy-dy;if(sx>=0&&sy>=0&&sx<64&&sy<64)d.set(old.slice((sy*64+sx)*4,(sy*64+sx+1)*4),(yy*64+xx)*4)}renderTexture();return}if(selection?.size){for(const k of selection){const[a,b]=k.split(',').map(Number);applyBrush(a,b)}}else applyBrush(x,y)}
skinCanvas.addEventListener('pointerdown',e=>{down=true;skinCanvas.setPointerCapture?.(e.pointerId);const p=point2D(e);strokeStart=p;strokeBase=cloneData();if(!['eyedropper','wand'].includes(tool))saveState();applyAt(...p);renderTexture()});skinCanvas.addEventListener('pointermove',e=>{const p=point2D(e);$('#cursorPos').textContent=`x: ${p[0]} y: ${p[1]}`;if(!down)return;if(tool==='line'||tool==='move'){d=new Uint8ClampedArray(strokeBase);applyAt(...p)}else applyAt(...p);renderTexture()});skinCanvas.addEventListener('pointerup',()=>{down=false;strokeStart=null;strokeBase=null;saveLocal()});skinCanvas.addEventListener('pointercancel',()=>{down=false;strokeStart=null;strokeBase=null});
skinCanvas.addEventListener('wheel',e=>{e.preventDefault();zoom2d=Math.max(2,Math.min(16,zoom2d+(e.deltaY<0?1:-1)));skinCanvas.style.width=`${64*zoom2d}px`;skinCanvas.style.height=`${64*zoom2d}px`;$('#zoomStatus').textContent=`${zoom2d*100/8|0}%`},{passive:false});
const regions={head:[[16,8,24,16],[0,8,8,16],[8,0,16,8],[16,0,24,8],[8,8,16,16],[24,8,32,16]],body:[[28,20,32,32],[16,20,20,32],[20,16,28,20],[28,16,36,20],[20,20,28,32],[32,20,40,32]],rightArm:[[48,20,52,32],[40,20,44,32],[44,16,48,20],[48,16,52,20],[44,20,48,32],[52,20,56,32]],leftArm:[[40,52,44,64],[32,52,36,64],[36,48,40,52],[40,48,44,52],[36,52,40,64],[44,52,48,64]],rightLeg:[[8,20,12,32],[0,20,4,32],[4,16,8,20],[8,16,12,20],[4,20,8,32],[12,20,16,32]],leftLeg:[[24,52,28,64],[16,52,20,64],[20,48,24,52],[24,48,28,52],[20,52,24,64],[28,52,32,64]]};
const outerRegions={head:[[48,8,56,16],[32,8,40,16],[40,0,48,8],[48,0,56,8],[40,8,48,16],[56,8,64,16]],body:[[36,36,40,48],[16,36,20,48],[20,32,28,36],[28,32,36,36],[20,36,28,48],[28,36,36,48]],rightArm:[[52,36,56,48],[40,36,44,48],[44,32,48,36],[48,32,52,36],[44,36,48,48],[48,36,52,48]],leftArm:[[44,52,48,64],[32,52,36,64],[36,48,40,52],[40,48,44,52],[36,52,40,64],[40,52,44,64]],rightLeg:[[8,36,12,48],[0,36,4,48],[4,32,8,36],[8,32,12,36],[4,36,8,48],[12,36,16,48]],leftLeg:[[28,52,32,64],[16,52,20,64],[20,48,24,52],[24,48,28,52],[20,52,24,64],[28,52,32,64]]};
function getRegions(name,outer=false){if(modelType==='slim'&&(name==='rightArm'||name==='leftArm'))return name==='rightArm'?[[47,20,50,32],[40,20,43,32],[44,16,47,20],[47,16,50,20],[44,20,47,32],[50,20,53,32]]:[[41,52,44,64],[32,52,35,64],[36,48,39,52],[39,48,42,52],[36,52,39,64],[42,52,45,64]];return(outer?outerRegions:regions)[name]}
function setBoxUV(geo,rs){const uv=geo.getAttribute('uv');for(let f=0;f<6;f++){const[a,b,c,e]=rs[f],u0=a/64,u1=c/64,v0=1-e/64,v1=1-b/64,off=f*6;[[u1,v0],[u0,v0],[u0,v1],[u1,v0],[u0,v1],[u1,v1]].forEach((v,i)=>uv.setXY(off+i,v[0],v[1]))}uv.needsUpdate=true}
function mat(){return new THREE.MeshStandardMaterial({map:texture,transparent:true,alphaTest:.01,roughness:.85,metalness:0})}
function makePart(name,size,pos,outer=false){const geo=new THREE.BoxGeometry(...size).toNonIndexed();setBoxUV(geo,getRegions(name,outer));const m=new THREE.Mesh(geo,mat());m.userData={part:name,outer};m.position.set(...pos);m.name=(outer?'outer-':'')+name;character.add(m);meshes[m.name]=m;return m}
function makeLimb(name,size,pivot,outer=false){const g=new THREE.Group();g.position.set(...pivot);g.name=(outer?'outer-':'')+name;character.add(g);partGroups[g.name]=g;const geo=new THREE.BoxGeometry(...size).toNonIndexed();setBoxUV(geo,getRegions(name,outer));const m=new THREE.Mesh(geo,mat());m.position.y=-size[1]/2;m.userData={part:name,outer};g.add(m);meshes[g.name]=m;return m}
function clearCharacter(){while(character.children.length)character.remove(character.children[0]);Object.keys(meshes).forEach(k=>delete meshes[k]);Object.keys(partGroups).forEach(k=>delete partGroups[k])}
function buildCharacter(){clearCharacter();const armW=modelType==='slim'?.75:1;makePart('head',[2,2,2],[0,5.4,0]);makePart('body',[2,2.6,1],[0,3.1,0]);makeLimb('rightArm',[armW,2.6,1],[-1.5,4,0]);makeLimb('leftArm',[armW,2.6,1],[1.5,4,0]);makeLimb('rightLeg',[1,2.6,1],[-.5,1.3,0]);makeLimb('leftLeg',[1,2.6,1],[.5,1.3,0]);makePart('head',[2.08,2.08,2.08],[0,5.4,0],true);makePart('body',[2.08,2.68,1.08],[0,3.1,0],true);makeLimb('rightArm',[armW+.1,2.7,1.08],[-1.5,4,0],true);makeLimb('leftArm',[armW+.1,2.7,1.08],[1.5,4,0],true);makeLimb('rightLeg',[1.08,2.7,1.08],[-.5,1.3,0],true);makeLimb('leftLeg',[1.08,2.7,1.08],[.5,1.3,0],true);applyVisibility();applyPose();fitCamera()}
function applyVisibility(){Object.values(meshes).forEach(m=>{m.visible=m.userData.outer?outerVisible:bodyVisible});$$('.part-eye').forEach(b=>{const m=meshes[b.dataset.part];b.classList.toggle('off',m?!m.visible:false)});$('#outerVis')?.classList.toggle('off',!outerVisible);$('#bodyVis')?.classList.toggle('off',!bodyVisible)}
function applyPose(){if(meshes.head){const r=new THREE.Euler(...pose.head.map(THREE.MathUtils.degToRad));meshes.head.rotation.copy(r);meshes['outer-head'].rotation.copy(r)}for(const p of ['leftArm','rightArm']){const a=THREE.MathUtils.degToRad(pose[p]);partGroups[p].rotation.z=a;partGroups['outer-'+p].rotation.z=a}}
function fitCamera(){cameraTarget.set(0,3.4,0);cameraDistance=9;cameraYaw=.35;cameraPitch=.04;updateCamera()}function updateCamera(){const cp=Math.cos(cameraPitch),lim=Math.PI/2-.08;cameraPitch=Math.max(-lim,Math.min(lim,cameraPitch));camera.position.set(cameraTarget.x+Math.sin(cameraYaw)*cp*cameraDistance,cameraTarget.y+Math.sin(cameraPitch)*cameraDistance,cameraTarget.z+Math.cos(cameraYaw)*cp*cameraDistance);camera.lookAt(cameraTarget);resizeRenderer()}function resizeRenderer(){const q=$('#viewport3d')?.getBoundingClientRect();if(!q||q.width<2||q.height<2)return;renderer.setSize(q.width,q.height,false);camera.aspect=q.width/q.height;camera.updateProjectionMatrix();renderer.render(scene,camera)}
function hit3D(e){const q=$('#threeCanvas').getBoundingClientRect();pointer.x=(e.clientX-q.left)/q.width*2-1;pointer.y=-(e.clientY-q.top)/q.height*2+1;raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(character.children,true).find(h=>h.object.visible&&h.object.userData.part)}
function paint3D(e){const hit=hit3D(e);if(!hit?.uv)return;const x=Math.max(0,Math.min(63,Math.floor(hit.uv.x*64))),y=Math.max(0,Math.min(63,Math.floor((1-hit.uv.y)*64)));$('#cursorPos').textContent=`x: ${x} y: ${y}`;if(tool==='eyedropper'){const c=get(x,y);fg='#'+c.slice(0,3).map(v=>v.toString(16).padStart(2,'0')).join('');$('#fgColor').value=fg;return}if(tool==='wand'){wandSelect(x,y);return}if(!down){down=true;saveState()}applyAt(x,y);renderTexture()}
const canvas3d=$('#threeCanvas');canvas3d.addEventListener('pointerdown',e=>{canvas3d.setPointerCapture?.(e.pointerId);cameraDrag={x:e.clientX,y:e.clientY,button:e.button,shift:e.shiftKey};if(e.button===0){down=false;paint3D(e)}});canvas3d.addEventListener('pointermove',e=>{if(!cameraDrag)return;const dx=e.clientX-cameraDrag.x,dy=e.clientY-cameraDrag.y;if(cameraDrag.button===2||cameraDrag.shift){cameraTarget.x-=dx*.01;cameraTarget.y+=dy*.01;updateCamera()}else if(down){paint3D(e)}else{cameraYaw-=dx*.01;cameraPitch-=dy*.01;updateCamera()}cameraDrag.x=e.clientX;cameraDrag.y=e.clientY});canvas3d.addEventListener('pointerup',()=>{if(down){down=false;saveLocal()}cameraDrag=null});canvas3d.addEventListener('pointercancel',()=>{down=false;cameraDrag=null});canvas3d.addEventListener('contextmenu',e=>e.preventDefault());canvas3d.addEventListener('wheel',e=>{e.preventDefault();cameraDistance=Math.max(5,Math.min(16,cameraDistance+e.deltaY*.012));updateCamera()},{passive:false});
function blank(){d.fill(0);for(let y=8;y<16;y++)for(let x=8;x<16;x++)px(x,y,[210,165,125,255]);for(let y=0;y<8;y++)for(let x=8;x<16;x++)px(x,y,[190,145,110,255]);for(let y=16;y<32;y++)for(let x=20;x<28;x++)px(x,y,[55,90,145,255]);for(let y=20;y<32;y++)for(let x=44;x<48;x++)px(x,y,[45,70,110,255]);for(let y=52;y<64;y++)for(let x=36;x<40;x++)px(x,y,[45,70,110,255]);for(let y=20;y<32;y++)for(let x=4;x<8;x++)px(x,y,[40,48,58,255]);for(let y=52;y<64;y++)for(let x=20;x<24;x++)px(x,y,[40,48,58,255]);undoStack=[];redoStack=[];selection=null;renderTexture();saveLocal()}
function importPNG(file){const im=new Image;im.onload=()=>{try{if(im.width!==64||im.height!==64){toast('Minecraft skin PNGs must be exactly 64×64');return}const z=document.createElement('canvas');z.width=z.height=64;const q=z.getContext('2d',{willReadFrequently:true});q.imageSmoothingEnabled=false;q.drawImage(im,0,0);d=new Uint8ClampedArray(q.getImageData(0,0,64,64).data);undoStack=[];redoStack=[];selection=null;renderTexture();saveLocal();toast('Skin imported')}finally{URL.revokeObjectURL(im.src)}};im.onerror=()=>toast('Could not read that PNG');im.src=URL.createObjectURL(file)}
function download(){const a=document.createElement('a');a.href=cleanPNGCanvas().toDataURL('image/png');a.download='skinforge-skin.png';a.click()}function toast(s){const q=$('#toast');if(!q)return;q.textContent=s;q.classList.add('show');setTimeout(()=>q.classList.remove('show'),1500)}
async function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('skinforge',2);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('skins'))req.result.createObjectStore('skins',{keyPath:'id'})};req.onsuccess=()=>{db=req.result;resolve()};req.onerror=reject})}function saveLocal(){if(!db)return;try{db.transaction('skins','readwrite').objectStore('skins').put({id:'current',texture:Array.from(d),updated:Date.now(),modelType})}catch(e){console.error('IndexedDB save failed',e)}}async function loadLocal(){if(!db)return;const item=await new Promise((resolve,reject)=>{const q=db.transaction('skins').objectStore('skins').get('current');q.onsuccess=()=>resolve(q.result);q.onerror=reject});if(item?.texture){d=new Uint8ClampedArray(item.texture);if(item.modelType==='classic'||item.modelType==='slim')modelType=item.modelType}}
function wireUI(){
$$('.tool').forEach(b=>b.onclick=()=>{$$('.tool').forEach(z=>z.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool;if(tool!=='clone')cloneSource=null});$('#brushSize').oninput=e=>brushSize=Math.max(1,Math.min(32,+e.target.value||1));$('#opacity').oninput=e=>{opacity=+e.target.value/100;$('#opacityOut').textContent=`${Math.round(opacity*100)}%`};$('#intensity').oninput=e=>{intensity=+e.target.value/100;$('#intensityOut').textContent=`${e.target.value}%`};$('#fgColor').oninput=e=>fg=e.target.value;$('#swapColors').onclick=()=>{const a=$('#fgColor'),b=$('#bgColor'),v=a.value;a.value=b.value;b.value=v;fg=a.value};['mirrorX','mirrorY','mirrorLimb'].forEach(id=>$('#'+id)?.onclick=()=>$('#'+id).classList.toggle('active'));
$('#gridBtn').onclick=()=>{grid=!grid;$('#gridBtn').classList.toggle('active',grid);renderTexture()};$('#uvBtn').onclick=()=>{uvOverlay=!uvOverlay;$('#uvBtn').classList.toggle('active',uvOverlay);renderTexture()};$('#fitBtn').onclick=fitCamera;$('#layerBtn').onclick=()=>{outerVisible=!outerVisible;applyVisibility();renderTexture()};$('#outerVis').onclick=()=>{$('#layerBtn').click()};$('#bodyVis').onclick=()=>{bodyVisible=!bodyVisible;applyVisibility();renderTexture()};$$('.part-eye').forEach(b=>b.onclick=()=>{const p=b.dataset.part,v=!meshes[p].visible;meshes[p].visible=v;meshes['outer-'+p].visible=v&&outerVisible;b.classList.toggle('off',!v)});
$('#resetPose').onclick=()=>{pose={head:[0,0,0],leftArm:0,rightArm:0};$$('[data-rot]').forEach(i=>i.value=0);$('#leftArmPose').value=0;$('#rightArmPose').value=0;applyPose();render3D()};$$('[data-rot]').forEach(i=>i.oninput=()=>{pose.head[['x','y','z'].indexOf(i.dataset.axis)]=+i.value||0;applyPose();render3D()});$('#leftArmPose').oninput=e=>{pose.leftArm=+e.target.value;applyPose();render3D()};$('#rightArmPose').oninput=e=>{pose.rightArm=+e.target.value;applyPose();render3D()};$('#savePose').onclick=()=>{localStorage.setItem('skinforge:pose',JSON.stringify(pose));toast('Pose saved locally')};
$('#newBtn').onclick=blank;$('#openBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{if(e.target.files[0])importPNG(e.target.files[0]);e.target.value=''};$('#downloadBtn').onclick=download;$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#fullscreenBtn').onclick=()=>document.documentElement.requestFullscreen?.();$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(z=>z.classList.remove('active'));b.classList.add('active');$('#viewport3d').classList.toggle('hidden',b.dataset.mode!=='3d');$('#viewport2d').classList.toggle('hidden',b.dataset.mode!=='2d');if(b.dataset.mode==='3d')resizeRenderer()});$$('.rtab').forEach(b=>b.onclick=()=>{$$('.rtab').forEach(z=>z.classList.remove('active'));b.classList.add('active');$$('.rpanel').forEach(p=>p.classList.add('hidden'));$('#'+b.dataset.rpanel+'Panel')?.classList.remove('hidden')});$('#modelType')?.addEventListener('change',e=>window.SkinForge.setModelType(e.target.value));
$('#importRefBtn')?.addEventListener('click',()=>$('#refInput').click());$('#refInput')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);referenceImage=new Image;referenceImage.onload=()=>{let old=$('#referenceOverlay');if(old)old.remove();const im=document.createElement('img');im.id='referenceOverlay';im.src=url;im.style.cssText='position:absolute;max-width:90%;max-height:90%;opacity:.35;pointer-events:none;image-rendering:auto';$('#canvasWrap').appendChild(im)};referenceImage.src=url;e.target.value=''});
$$('[data-menu]').forEach(b=>b.onclick=()=>{const m={file:[['New',blank],['Open',()=>$('#fileInput').click()],['Export PNG',download]],edit:[['Undo',undo],['Redo',redo]],view:[['Fullscreen',()=>document.documentElement.requestFullscreen?.()],['Grid',()=>$('#gridBtn').click()],['Fit',fitCamera]],settings:[['Model',()=>$('#modelType')?.focus()]],help:[['About',()=>alert('SkinForge — browser-based Minecraft skin editor.')]]}[b.dataset.menu],p=$('#menuPanel');if(!m)return;p.innerHTML=m.map(z=>`<button>${z[0]}</button>`).join('');p.classList.remove('hidden');p.querySelectorAll('button').forEach((z,i)=>z.onclick=()=>{p.classList.add('hidden');m[i][1]()})});window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.key==='['){brushSize=Math.max(1,brushSize-1);$('#brushSize').value=brushSize}else if(e.key===']'){brushSize=Math.min(32,brushSize+1);$('#brushSize').value=brushSize}});window.addEventListener('resize',resizeRenderer);window.addEventListener('offline',()=>$('#syncState').textContent='Offline');window.addEventListener('online',()=>$('#syncState').textContent=window.SkinCloud?.user?'Cloud ready':'Local')}
async function init(){try{await openDB();await loadLocal()}catch(e){console.error('Local storage initialization failed',e)}const sp=localStorage.getItem('skinforge:pose');if(sp)try{pose=JSON.parse(sp)}catch{}if(!d.some(Boolean))blank();wireUI();buildCharacter();renderTexture();resizeRenderer()}init();